<?php
/**
 * @package Livedocx
 */
class Livedocx_Widget extends WP_Widget {

	function __construct() {
		load_plugin_textdomain( 'livedocx' );
		
		parent::__construct(
			'livedocx_widget',
			__( 'Livedocx Widget' , 'livedocx'),
			array( 'description' => __( 'Display the form for sending to user generated by Livedocx template PDF by email' , 'livedocx') )
		);

		if ( is_active_widget( false, false, $this->id_base ) ) {
			add_action( 'wp_head', array( $this, 'css' ) );
		}
	}

	function css() {
?>

<style type="text/css">
.a-stats {
	width: auto;
}
.a-stats a {
	background: #7CA821;
	background-image:-moz-linear-gradient(0% 100% 90deg,#5F8E14,#7CA821);
	background-image:-webkit-gradient(linear,0% 0,0% 100%,from(#7CA821),to(#5F8E14));
	border: 1px solid #5F8E14;
	border-radius:3px;
	color: #CFEA93;
	cursor: pointer;
	display: block;
	font-weight: normal;
	height: 100%;
	-moz-border-radius:3px;
	padding: 7px 0 8px;
	text-align: center;
	text-decoration: none;
	-webkit-border-radius:3px;
	width: 100%;
}
.a-stats a:hover {
	text-decoration: none;
	background-image:-moz-linear-gradient(0% 100% 90deg,#6F9C1B,#659417);
	background-image:-webkit-gradient(linear,0% 0,0% 100%,from(#659417),to(#6F9C1B));
}
.a-stats .count {
	color: #FFF;
	display: block;
	font-size: 15px;
	line-height: 16px;
	padding: 0 13px;
	white-space: nowrap;
}
</style>

<?php
	}

	function form( $instance ) {
		if ( $instance ) {
			$title = $instance['title'];
		}
		else {
			$title = __( 'PDF generator' , 'livedocx');
		}
?>

		<p>
		<label for="<?php echo $this->get_field_id( 'title' ); ?>"><?php esc_html_e( 'Title:' , 'livedocx'); ?></label>
		<input class="widefat" id="<?php echo $this->get_field_id( 'title' ); ?>" name="<?php echo $this->get_field_name( 'title' ); ?>" type="text" value="<?php echo esc_attr( $title ); ?>" />
		</p>

<?php
	}

	function update( $new_instance, $old_instance ) {
		$instance['title'] = strip_tags( $new_instance['title'] );
		return $instance;
	}

	function widget( $args, $instance ) {

		echo $args['before_widget'];
		if ( ! empty( $instance['title'] ) ) {
			echo $args['before_title'];
			echo esc_html( $instance['title'] );
			echo $args['after_title'];
		}
		if ( ( $_SERVER['REQUEST_METHOD'] === 'POST' ) && ! empty( $_POST['livedocx_name'] ) && ! empty( $_POST['livedocx_email'] ) ) {
			echo Livedocx::livedocx_demo_form($_POST['livedocx_name'], $_POST['livedocx_email']);
		}

		?>
		<form method="post">
			<label for="livedocx_name">Your name:</label>
			<input type="text" name="livedocx_name"/>
			<label for="livedocx_email">Your Email:</label>
			<input type="text" name="livedocx_email"/>
			<br/>
			<br/>
			<input type="submit" value="Send PDF"/>
		</form>
	<?php

		echo $args['after_widget'];
	}
}

function livedocx_register_widgets() {
	register_widget( 'Livedocx_Widget' );
}

add_action( 'widgets_init', 'livedocx_register_widgets' );
